# -*- coding: utf-8 -*-
"""lab14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaB53FkKe4I50o6-w_laEpqusb9XKAWA
"""

!pip -q install "pymc>=5" arviz pytensor

import os
import numpy as np
import pandas as pd
import pymc as pm
import arviz as az
import matplotlib.pyplot as plt

np.random.seed(123)
az.style.use("arviz-whitegrid")

csv_path = "date_colesterol.csv"
if not os.path.exists(csv_path):
    from google.colab import files
    uploaded = files.upload()
    if len(uploaded) == 0:
        raise FileNotFoundError("Nu am gasit date_colesterol.csv si nu s-a incarcat niciun fisier.")
    csv_path = list(uploaded.keys())[0]

df = pd.read_csv(csv_path)

cols = list(df.columns)
if len(cols) < 2:
    raise ValueError("CSV trebuie sa aiba cel putin 2 coloane: ore_exercitiu si colesterol.")
x = df[cols[0]].to_numpy(dtype=float)
y = df[cols[1]].to_numpy(dtype=float)

x = x - x.mean()

K_list = [3, 4, 5]
idatas = {}

# Subpunctul 1
for K in K_list:
    with pm.Model() as model:
        p = pm.Dirichlet("p", a=np.ones(K))

        alpha = pm.Normal(
            "alpha",
            mu=np.linspace(y.min(), y.max(), K),
            sigma=20,
            shape=K,
            transform=pm.distributions.transforms.ordered,
        )
        beta = pm.Normal("beta", mu=0, sigma=10, shape=K)
        gamma = pm.Normal("gamma", mu=0, sigma=10, shape=K)
        sigma = pm.HalfNormal("sigma", sigma=20, shape=K)

        x_data = pm.Data("x", x)
        mu = alpha + beta * x_data[:, None] + gamma * (x_data**2)[:, None]

        y_obs = pm.NormalMixture("y_obs", w=p, mu=mu, sigma=sigma, observed=y)

        idata = pm.sample(
            draws=1500,
            tune=2500,
            chains=4,
            target_accept=0.95,
            random_seed=123,
            return_inferencedata=True,
            idata_kwargs={"log_likelihood": True},
        )

    idatas[str(K)] = idata

    print("\n=======================")
    print(f"K = {K}")
    print(az.summary(idata, var_names=["p", "alpha", "beta", "gamma", "sigma"]))

# Subpunctul 2
cmp_waic = az.compare(idatas, ic="waic", scale="deviance", method="BB-pseudo-BMA")
cmp_loo  = az.compare(idatas, ic="loo",  scale="deviance", method="BB-pseudo-BMA")

print("\n\n=== Comparatie WAIC (mai mic e mai bun) ===")
print(cmp_waic)

print("\n\n=== Comparatie LOO (mai mic e mai bun) ===")
print(cmp_loo)

best_waic = cmp_waic.index[0]
best_loo = cmp_loo.index[0]
print(f"\nBest dupa WAIC: K = {best_waic}")
print(f"Best dupa LOO : K = {best_loo}")

az.plot_compare(cmp_waic)
plt.show()

az.plot_compare(cmp_loo)
plt.show()

for K in K_list:
    idata = idatas[str(K)]
    az.plot_trace(idata, var_names=["p", "alpha", "beta", "gamma", "sigma"])
    plt.show()