# -*- coding: utf-8 -*-
"""lab10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-I3q35qxlxRXWVnNLoPcJWTEqGz4orxa
"""

!pip install -q "pymc>=5" "arviz>=0.15"

import numpy as np
import pymc as pm
import arviz as az


publicity = np.array([
    1.5, 2.0, 2.3, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0,
    6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 10.5, 11.0
])

sales = np.array([
    5.2, 6.8, 7.5, 8.0, 9.0, 10.2, 11.5, 12.0, 13.5, 14.0,
    15.0, 15.5, 16.2, 17.0, 18.0, 18.5, 19.5, 20.0, 21.0, 22.0
])


new_publicity = np.array([2.0, 6.0, 10.0])


with pm.Model() as model:

    x = pm.MutableData("publicity", publicity)


    alpha = pm.Normal("alpha", mu=0, sigma=20)
    beta  = pm.Normal("beta",  mu=0, sigma=10)
    sigma = pm.HalfNormal("sigma", sigma=5)


    mu = alpha + beta * x


    pm.Normal("sales", mu=mu, sigma=sigma, observed=sales)


    idata = pm.sample(2000, tune=1000, target_accept=0.9, random_seed=1)


# a)
print("\nRezumat posterior pentru coeficienți (alpha, beta, sigma):")
print(az.summary(idata, var_names=["alpha", "beta", "sigma"], hdi_prob=0.95))


# b)
coef_hdi = az.hdi(idata, var_names=["alpha", "beta"], hdi_prob=0.95)
print("\nHDI 95% pentru coeficienți (alpha, beta):")
print(coef_hdi)


# c)
posterior = idata.posterior

alpha_s = posterior["alpha"].stack(sample=("chain", "draw")).values
beta_s  = posterior["beta"].stack(sample=("chain", "draw")).values
sigma_s = posterior["sigma"].stack(sample=("chain", "draw")).values

rng = np.random.default_rng(1)

print("\nIntervale predictive 90% (5%, 95%) pentru new_publicity:")
for p in new_publicity:
    mu_p = alpha_s + beta_s * p
    y_pred = rng.normal(mu_p, sigma_s)
    lo, hi = np.percentile(y_pred, [5, 95])

    print(f"publicity = {p:4.1f} -> sales ~ {lo:5.2f} .. {hi:5.2f} (mii $)")