# -*- coding: utf-8 -*-
"""lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vzWhljMRMh7aKD41C6IwM5vmMG0fpHu
"""

import numpy as np
import pymc as pm
import arviz as az
import matplotlib.pyplot as plt

data = np.array([56, 60, 58, 55, 57, 59, 61, 56, 58, 60])

x_bar = data.mean()
s_hat = data.std(ddof=1)


print("date si statistici descriptive (estimari frecventiste)")
print(f"media esantionului    = {x_bar:.2f}")
print(f"deviatia std. esant.  = {s_hat:.2f}\n")

# a)

print("a) model bayesian cu prior slab (μ ~ N(x̄, 10^2))")
print(f"x (centrul priorului pentru μ) = x̄ = {x_bar:.2f}\n")

with pm.Model() as weak_model:
    mu = pm.Normal("mu", mu=x_bar, sigma=10)
    sigma = pm.HalfNormal("sigma", sigma=10)
    y = pm.Normal("y", mu=mu, sigma=sigma, observed=data)

    # b)
    trace_weak = pm.sample(
        draws=2000,
        tune=2000,
        target_accept=0.9,
        random_seed=42
    )

summary_weak = az.summary(
    trace_weak,
    var_names=["mu", "sigma"],
    hdi_prob=0.95
)

print("rezumat posterior (prior slab):")
print(summary_weak, "\n")

mu_hdi_low = summary_weak.loc["mu", "hdi_2.5%"]
mu_hdi_high = summary_weak.loc["mu", "hdi_97.5%"]
sg_hdi_low = summary_weak.loc["sigma", "hdi_2.5%"]
sg_hdi_high = summary_weak.loc["sigma", "hdi_97.5%"]

print("interpretare b) – 95% HDI:")
print(f"  - HDI 95% pentru μ  ≈ [{mu_hdi_low:.2f}, {mu_hdi_high:.2f}]")
print(f"  - HDI 95% pentru σ  ≈ [{sg_hdi_low:.2f}, {sg_hdi_high:.2f}]\n")

az.plot_posterior(trace_weak, var_names=["mu", "sigma"], hdi_prob=0.95)
plt.suptitle("posterior pentru μ și σ – prior slab", fontsize=14)
plt.show()

# c)

print("c) comparatie cu estimările frecventiste")
print("Estimari frecventiste (din date):")
print(f"  media (mean)        = {x_bar:.2f}")
print(f"  deviatia std. (ŝ)  = {s_hat:.2f}\n")

print("estimari bayesiene (prior slab) – din rezumatul posterior:")
print(summary_weak, "\n")

print("  - media posteriora a lui μ ar trebui sa fie foarte aproape de media esantionului.")
print("  - media posteriora a lui σ poate fi usor diferita de deviatia standard esantionala,deoarece este influentata si de priorul HalfNormal(10).\n")