# -*- coding: utf-8 -*-
"""partial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZRDQwd9lAMRBouTEVWtj5jP9co0dYIw
"""

from pgmpy.models import BayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import VariableElimination

model = BayesianNetwork([
    ('O', 'H'), ('O', 'W'), ('H', 'R'), ('W', 'R'),  ('H', 'E'),  ('R', 'C')
])


cpd_O = TabularCPD(
    variable='O',
    variable_card=2,
    values=[[0.3], [0.7]],
    state_names={'O': ['cold', 'mild']}
)

# CPD H | O
cpd_H = TabularCPD(
    variable='H',
    variable_card=2,
    values=[
        [0.9, 0.2],   # H = yes
        [0.1, 0.8]    # H = no
    ],
    evidence=['O'],
    evidence_card=[2],
    state_names={'H': ['yes', 'no'], 'O': ['cold', 'mild']}
)

# CPD W | O
cpd_W = TabularCPD(
    variable='W',
    variable_card=2,
    values=[
        [0.1, 0.6],   # W = yes
        [0.9, 0.4]    # W = no
    ],
    evidence=['O'],
    evidence_card=[2],
    state_names={'W': ['yes', 'no'], 'O': ['cold', 'mild']}
)

# CPD R | H, W
cpd_R = TabularCPD(
    variable='R',
    variable_card=2,
    values=[
        [0.9, 0.6, 0.3, 0.5],  # R = warm
        [0.1, 0.4, 0.7, 0.5]   # R = cool
    ],
    evidence=['H', 'W'],
    evidence_card=[2, 2],
    state_names={'R': ['warm', 'cool'],
                 'H': ['yes', 'no'],
                 'W': ['yes', 'no']}
)

# CPD E | H
cpd_E = TabularCPD(
    variable='E',
    variable_card=2,
    values=[
        [0.8, 0.2],  # E = high
        [0.2, 0.8]   # E = low
    ],
    evidence=['H'],
    evidence_card=[2],
    state_names={'E': ['high', 'low'], 'H': ['yes', 'no']}
)

# CPD C | R
cpd_C = TabularCPD(
    variable='C',
    variable_card=2,
    values=[
        [0.85, 0.40],  # C = comfortable
        [0.15, 0.60]   # C = uncomfortable
    ],
    evidence=['R'],
    evidence_card=[1],
    state_names={'C': ['comfortable', 'uncomfortable'], 'R': ['warm', 'cool']}
)

model.add_cpds(cpd_O, cpd_H, cpd_W, cpd_R, cpd_E, cpd_C)


print(model.check_model())

